name: 'Terraform'

on:
  push:
  pull_request:

jobs:
  terraform-aws:
    name: 'Terraform AWS'
    runs-on: ubuntu-latest
    environment: production


    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Install and build frontend dependencies
      run: |
        cd frontend
        npm install
        npm run build:ci
      env: 
        CI: false

    - name: Create Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: frontend/build

    - name: Package Functions Directory
      run: |
        mkdir -p package_dirs
        cd backend
        for folder in lambda_functions/*; do
          if [[ -d "$folder" ]]; then
            echo "current dir: $folder"
            pkg_dir="./${folder}_pkg"
            pip install --target $pkg_dir gspread
            echo "installed gspread to $pkg_dir. "
            cp -r "utils" $pkg_dir
            cp -r "models" $pkg_dir
            cp -r $folder $pkg_dir
            echo "copied utils and models"
            cp -r $pkg_dir ../package_dirs
          fi
        done

    - name: Create Directory Artifact
      uses: actions/upload-artifact@v2
      with:
        name: package-dirs
        path: package_dirs

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform Validate
      run: terraform -chdir=terraform validate 

    - name: testing package_dirs 
      run: |
        cd frontend
        ls

    - name: Terraform Plan
      run: |
        ls
        terraform -chdir=terraform plan -input=false

    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve -input=false
      