name: 'Terraform'

on:
  push:
    branches:
  pull_request:

jobs:
  deploy-lambda:
    name: 'Deploy Lambda'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Package Functions
      run: |
        for file in backend/lambda_functions/*; do
          if [[ -f "$file" ]]; then
            echo "file found"
            echo "$file"
          fi
          echo "test"
        done



  # terraform-aws:
  #   name: 'Terraform AWS'
  #   runs-on: ubuntu-latest
  #   environment: production


  #   defaults:
  #     run:
  #       shell: bash

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3

  #   - name: Setup Terraform
  #     uses: hashicorp/setup-terraform@v1
  #     with:
  #       cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  #   - name: Terraform Init
  #     run: terraform -chdir=terraform init

  #   - name: Terraform Validate
  #     run: terraform -chdir=terraform validate 

  #   - name: Terraform Plan
  #     run: terraform -chdir=terraform plan -input=false

  #   - name: Terraform Apply
  #     run: terraform -chdir=terraform apply -auto-approve -input=false
      